name: seamain ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker-publish:
    uses: dockerfiles/.github/workflows/docker-publish-ghcr.yml@main
    with:
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      tags: ghcr.io/${{ github.repository_owner }}/cacti-backend:latest
    secrets: inherit
