name: seamine ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker-publish:
    uses: mura/dockerfiles/.github/workflows/docker-publish-ghcr.yml@main
    with:
      platforms: linux/amd64,linux/arm64
      tags: ghcr.io/${{ github.repository_owner }}/seamine:latest
    secrets: inherit
